wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692449606.061493
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 19
      - 23
      - 24
      4: 3.10.11
      5: 0.15.4
      8:
      - 5
learning_rate:
  desc: null
  value: 0.0001
window_size:
  desc: null
  value: 100
embedding_size:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 4
num_workers:
  desc: null
  value: 16
input_shape:
  desc: null
  value:
  - 1
  - 100
  - 8
embedding_shape:
  desc: null
  value:
  - 1
  - 8
num_layers:
  desc: null
  value: 5
num_heads:
  desc: null
  value: 8
