wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691512797.156147
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 19
      - 23
      - 24
      4: 3.10.11
      5: 0.15.4
      8:
      - 5
learning_rate:
  desc: null
  value: 1.0e-06
window_size:
  desc: null
  value: 1000
embedding_size:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 4
num_workers:
  desc: null
  value: 16
